version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Maven Tests with Coverage
          command: mvn clean verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Generate Checkstyle Badge from GitHub
          command: |
            CHECKSTYLE_URL="https://raw.githubusercontent.com/MejaiWajdi/ceri-m1-techniques-de-test/master/target/checkstyle-result.xml"
            
            # Vérifier si le fichier existe sur GitHub
            if ! curl --output /dev/null --silent --head --fail "$CHECKSTYLE_URL"; then
              echo "Checkstyle result file not found on GitHub!"
              exit 1
            fi
            
            # Compter les erreurs directement depuis l'URL
            ERRORS=$(curl -s "$CHECKSTYLE_URL" | grep -c "<error ")
            
            # Définir les couleurs et messages pour le badge
            if [ "$ERRORS" -eq 0 ]; then
              COLOR="green"
              MESSAGE="Passing"
            else
              COLOR="red"
              MESSAGE="$ERRORS errors"
            fi
            
            # Générer le badge avec shields.io
            curl -s "https://img.shields.io/badge/Checkstyle-$MESSAGE-$COLOR.svg" -o checkstyle-badge.svg
      - store_artifacts:
          path: checkstyle-badge.svg
          destination: checkstyle-badge

workflows:
  build-and-test:
    jobs:
      - test-java
