version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Maven Tests with Coverage
          command: mvn clean verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - run:
          name: Generate Checkstyle Badge
          command: |
            if [ ! -f target/checkstyle-result.xml ]; then
              echo "Checkstyle result file not found!"
              exit 1
            fi

            ERRORS=$(grep -c "<error " target/checkstyle-result.xml)

            if [ "$ERRORS" -eq 0 ]; then
              COLOR="green"
              MESSAGE="Passing"
            else
              COLOR="red"
              MESSAGE="$ERRORS errors"
            fi

            curl -s "https://img.shields.io/badge/Checkstyle-$MESSAGE-$COLOR.svg" -o checkstyle-badge.svg
      - store_artifacts:
          path: checkstyle-badge.svg
          destination: badges
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: reports/checkstyle

workflows:
  build-and-test:
    jobs:
      - test-java
