version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Maven Tests with Coverage
          command: mvn clean verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Make generate-badge.sh executable
          command: chmod +x ./generate-badge.sh
      - run:
          name: Run Generate Badge Script
          command: bash ./generate-badge.sh
      - store_artifacts:
          path: checkstyle-badge.svg
          destination: ./checkstyle-badge
      - run:
          name: upload_badge_to_github
          command: bash ./upload-badge-to-github.sh

workflows:
  build-and-test:
    jobs:
      - test-java

