version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Maven Tests with Coverage
          command: mvn clean verify
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Make generate-badge.sh executable
          command: chmod +x ./generate-badge.sh
      - run:
          name: Run Generate Badge Script
          command: bash ./generate-badge.sh
      - store_artifacts:
          path: checkstyle-badge.svg
          destination: ./checkstyle-badge
      - run:
          name: upload_badge_to_github
          command: bash ./upload-badge-to-github.sh
  generate-docs:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Configure Git for GitHub Pages
          command: |
            git config --global user.email "your-email@example.com"
            git config --global user.name "Your Name"
      - run:
          name: Create gh-pages Branch If Not Exists
          command: |
            git fetch origin
            if ! git rev-parse --verify origin/gh-pages; then
              git checkout --orphan gh-pages
              git rm -rf .
              echo "Placeholder for GitHub Pages" > index.html
              git add index.html
              git commit -m "Initial commit for GitHub Pages"
             git push https://$GITHUB_TOKEN@github.com/MejaiWajdi/ceri-m1-techniques-de-test.git gh-pages
            fi
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            mkdir -p output
            mv target/site/apidocs/* output/
            git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/MejaiWajdi/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages
            rm -rf *
            mv ../output/* .
            git add .
            git commit -m "Update Javadoc"
            git push https://$GITHUB_TOKEN@github.com/MejaiWajdi/ceri-m1-techniques-de-test.git gh-pages

workflows:
  build-and-test:
    jobs:
      - test-java
      - generate-docs

